name: push script

on:
  push:
    branches: [ main ]
  
env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  ID_TOKEN: ${{ secrets.ID_TOKEN }}
  CLIENTID: ${{ secrets.CLIENTID }}
  CLIENTSECRET: ${{ secrets.CLIENTSECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
    - run: yarn install --frozen-lock
    - run: |
        cat << EOF > ~/.clasprc.json.tmpl
        {
          "token": {
            "access_token": "${ACCESS_TOKEN}",
            "refresh_token": "${REFRESH_TOKEN}",
            "scope":  "https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/userinfo.email openid",
            "token_type": "Bearer",
            "id_token": "${ID_TOKEN}",
            "expiry_date": 1720019054006
          },
          "oauth2ClientSettings": {
            "clientId": "${CLIENTID}",
            "clientSecret": "${CLIENTSECRET}",
            "redirectUri": "http://localhost"
          },
          "isLocalCreds": false
        }
        EOF
    - run: envsubst < ~/.clasprc.json.tmpl > ~/.clasprc.json
    - run: yarn clasp push
